# frozen_string_literal: true

require_relative "grimoire/version"
require_relative "grimoire/errors"
require_relative "grimoire/config"
require_relative "grimoire/domain/note"
require_relative "grimoire/domain/notes_repository"
require_relative "grimoire/domain/search_result"
require_relative "grimoire/domain/link_resolver"
require_relative "grimoire/application/services/note_catalog"
require_relative "grimoire/application/services/search_notes"
require_relative "grimoire/infrastructure/filesystem/notes_repository"
require_relative "grimoire/presentation/formatter"
require_relative "grimoire/presentation/tui"
require_relative "grimoire/cli"
